#!/bin/bash
# rsync current dir into windows space, then run the passed args in powershell
# example usage psh python main.py

directory_name=${PWD##*/}
tmp_path="/mnt/c/Windows/temp/$directory_name"

mkdir -p $tmp_path

rsync . $tmp_path -rc --exclude-from=.gitignore --exclude=.git/*

cd $tmp_path

while [[ "$1" == -* ]]; do
 case $1 in
   i)
     powershell.exe -Command "pip install ."
     ;;
   x)
     powershell.exe -Command "python -m PyInstaller --onefile --hide-console hide-early -n maleficer .\\src\\main.py"
   ;;
   \?)
     echo "invalid option"
   ;;
 esac
 shift
done

powershell.exe -Command "$@"
