
CONSOLE_WIDTH = 1920
CONSOLE_HEIGHT = 1080
TILE_SIZE = 10
BOARD_HEIGHT = CONSOLE_HEIGHT//TILE_SIZE
BOARD_WIDTH = CONSOLE_WIDTH//TILE_SIZE

PANEL_WIDTH = 50
PANEL_HEIGHT = 103 # 5 less than board height for task bar, change when full screen
